//AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_PASSWORD = "SET_PASSWORD";
//TASKS
export const FETCH_OWNED_TASKS = "FETCH_OWNED_TASKS";
export const FETCH_DRAWN_TASKS = "FETCH_DRAWN_TASKS";
export const FETCH_FINISHED_TASKS = "FETCH_FINISHED_TASKS";
export const TOGGLE_HIDDEN = "TOGGLE_HIDDEN";
export const DELETE_TASK = "DELETE_TASK";
export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";
export const EDIT_TASK = "EDIT_TASK";
export const EDIT_TASK_FAIL = "EDIT_TASK_FAIL";
export const DRAW_TASK = "DRAW_TASK";
export const DRAW_TASK_FAIL = "DRAW_TASK_FAIL";
export const FINISH_TASK = "FINISH_TASK";
//USER
export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const SET_EMAIL = "SET_EMAIL";
export const SET_EMAIL_FAIL = "SET_EMAIL_FAIL";